LIB=mem.obj hash.obj lists.obj symbol.obj world.obj shape.obj objects.obj mobile.obj bangs.obj bullets.obj explo.obj ground.obj smoke.obj
FLAGS= /zq /oxt /l=dos4g /bt=dos /i=..\graphw /i=..\io

world: $(LIB)

.c.obj:
	wcl386 $(FLAGS) -c $*
